FROM nginx:1.27-alpine

LABEL maintainer="Johan Sebastian Rodriguez"
LABEL description="Servidor web del proyecto final para validar comunicacion entre contenedores Docker"

COPY index.html /usr/share/nginx/html/index.html

EXPOSE 80
