FROM nginx:1.27-alpine

LABEL maintainer="Grupo Integración Continua"
LABEL description="Servidor web simple para validar comunicación entre contenedores Docker"

COPY index.html /usr/share/nginx/html/index.html

EXPOSE 80
